/*
 * PanelFlags.java
 *
 
 */

package ensea.simulateurSTM32.ihm.Panel;

/**
 *
 * @author  Betty && Samira
 */
import ensea.simulateurSTM32.ihm.Ihm;

/**
 *
 * Etat des drapeaux
 */

public class PanelFlags extends javax.swing.JPanel {

    
    Ihm ihm;

    //Drapeaux
    int n;
    int z;
    int p;
    int c;
    int v;

    
    /** Creates new form PanelFlags */
    public PanelFlags(Ihm ihmParam) {
        ihm = ihmParam;
        initComponents();
    }

    public int getN() {
        return n;
    }

    public int getP() {
        return p;
    }

    public int getZ() {
        return z;
    }

    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jToolBarN = new javax.swing.JToolBar();
        jLabelN = new javax.swing.JLabel();
        jRadioButtonN = new javax.swing.JRadioButton();
        jToolBarZ = new javax.swing.JToolBar();
        jLabelZ = new javax.swing.JLabel();
        jRadioButtonZ = new javax.swing.JRadioButton();
        jToolBarV = new javax.swing.JToolBar();
        jLabelV = new javax.swing.JLabel();
        jRadioButtonV = new javax.swing.JRadioButton();
        jToolBarC = new javax.swing.JToolBar();
        jLabelC = new javax.swing.JLabel();
        jRadioButtonC = new javax.swing.JRadioButton();

        jLabel2.setText("jLabel2");

        setForeground(new java.awt.Color(204, 0, 51));

        jToolBarN.setBorder(null);
        jToolBarN.setRollover(true);

        jLabelN.setText("N");
        jLabelN.setFocusable(false);
        jToolBarN.add(jLabelN);

        jRadioButtonN.setForeground(new java.awt.Color(255, 0, 0));
        jRadioButtonN.setEnabled(false);
        jRadioButtonN.setFocusable(false);
        jRadioButtonN.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jRadioButtonN.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarN.add(jRadioButtonN);

        jToolBarZ.setBorder(null);
        jToolBarZ.setRollover(true);

        jLabelZ.setText("Z");
        jToolBarZ.add(jLabelZ);

        jRadioButtonZ.setForeground(new java.awt.Color(255, 102, 51));
        jRadioButtonZ.setEnabled(false);
        jRadioButtonZ.setFocusable(false);
        jRadioButtonZ.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jRadioButtonZ.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarZ.add(jRadioButtonZ);

        jToolBarV.setBorder(null);
        jToolBarV.setRollover(true);

        jLabelV.setText("V");
        jToolBarV.add(jLabelV);

        jRadioButtonV.setForeground(new java.awt.Color(255, 0, 0));
        jRadioButtonV.setEnabled(false);
        jRadioButtonV.setFocusable(false);
        jRadioButtonV.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jRadioButtonV.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarV.add(jRadioButtonV);

        jToolBarC.setBorder(null);
        jToolBarC.setRollover(true);

        jLabelC.setText("C");
        jToolBarC.add(jLabelC);

        jRadioButtonC.setForeground(new java.awt.Color(255, 0, 0));
        jRadioButtonC.setEnabled(false);
        jRadioButtonC.setFocusable(false);
        jRadioButtonC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jRadioButtonC.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarC.add(jRadioButtonC);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBarN, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToolBarZ, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToolBarV, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToolBarC, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBarZ, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToolBarV, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToolBarC, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToolBarN, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    /**private void jButtonInitRAMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInitRAMActionPerformed
        this.ihm.LCM3simulator.initValRAM(0x20000000,1);
        this.ihm.LCM3simulator.initValRAM(0x20000004,2);
        this.ihm.panelRAM.dispVal(0, 1);
        this.ihm.panelRAM.dispVal(1, 2);
    }//GEN-LAST:event_jButtonInitRAMActionPerformed
    private void jButtonInitRAMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInitRAMActionPerformed
        this.ihm.LCM3simulator.initValRAM(0x20000000,1);
        this.ihm.LCM3simulator.initValRAM(0x20000004,2);
        this.ihm.panelRAM.dispVal(0, 1);
        this.ihm.panelRAM.dispVal(1, 2);
    }//GEN-LAST:event_jButtonInitRAMActionPerformed
     **/
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelC;
    private javax.swing.JLabel jLabelN;
    private javax.swing.JLabel jLabelV;
    private javax.swing.JLabel jLabelZ;
    private javax.swing.JRadioButton jRadioButtonC;
    private javax.swing.JRadioButton jRadioButtonN;
    private javax.swing.JRadioButton jRadioButtonV;
    private javax.swing.JRadioButton jRadioButtonZ;
    private javax.swing.JToolBar jToolBarC;
    private javax.swing.JToolBar jToolBarN;
    private javax.swing.JToolBar jToolBarV;
    private javax.swing.JToolBar jToolBarZ;
    // End of variables declaration//GEN-END:variables
    
    public void setAffichageFlag(boolean n, boolean z, boolean p) {
        jRadioButtonN.setSelected(n);
        jRadioButtonZ.setSelected(z);
        

        if (n) this.n=1;
        else this.n=0;
        if (p) this.p=1;
        else this.p=0;
        if (z) this.z=1;
        else this.z=0;
       
        
    }
    
    public void affFlags(int flagN, int flagZ, int flagV, int flagC) {
        if(flagN==1)
            jRadioButtonN.setSelected(true);
        if(flagN==0)
            jRadioButtonN.setSelected(false);       
        if(flagZ==1)
            jRadioButtonZ.setSelected(true);
        if(flagZ==0)
            jRadioButtonZ.setSelected(false);       
        if(flagV==1)
            jRadioButtonV.setSelected(true);
        if(flagV==0)
            jRadioButtonV.setSelected(false);       
        if(flagC==1)
            jRadioButtonC.setSelected(true);
        if(flagC==0)
            jRadioButtonC.setSelected(false);       
        
    }

        //modifie l'affichage des drapeaux

        public void setAffichageFlag2(boolean c, boolean v) {
        jRadioButtonC.setSelected(c);
        jRadioButtonV.setSelected(v);

        if (c) this.c=1;
        else this.c=0;
        if (v) this.v=1;
        else this.v=0;



    }


        
}
