/*
 * PanelBouttons.java
 */

/* *    Choix de l'execution PasàPas -Reset - 
 * @author  Guillaume - Vincent
 */

package ensea.simulateurSTM32.ihm.Panel;

import ensea.simulateurSTM32.LCM3.Modification;
import ensea.simulateurSTM32.ihm.Ihm;
import java.awt.Color;

import ensea.simulateurSTM32.LCM3.EtatPipeline;


/**
Choix de l'execution Pas à Pas -Reset - 
 */


public class PanelBouttons extends javax.swing.JPanel {
    // Adresse de base de la mémoire ROM du STM32
    private static final int ROM_BASE_ADDRESS = 0x08000000;  // 134217728 en décimal
    
    // Constantes pour le pipeline
    private static final int INSTRUCTION_SIZE = 2;           // Taille d'une instruction en octets
    private static final int FETCH_OFFSET = ROM_BASE_ADDRESS;                    // 0x08000000 (134217728)
    private static final int DECODE_OFFSET = ROM_BASE_ADDRESS + INSTRUCTION_SIZE; // 0x08000002 (134217730)
    private static final int EXECUTE_OFFSET = ROM_BASE_ADDRESS + (INSTRUCTION_SIZE * 3); // 0x08000006 (134217734)
    private static final int PIPELINE_STEP = 5;             // Incrément pour les étapes du pipeline
    
    // Méthode utilitaire pour formater l'affichage d'une adresse du pipeline
    private String formatPipelineAddress(int address) {
        if (address == -1) {
            return "Pipeline vide";
        }
        String stage = "";
        String hex = String.format("0x%08X", address);
        
        if (address == FETCH_OFFSET) {
            stage = "Fetch";
        } else if (address == DECODE_OFFSET) {
            stage = "Decode";
        } else if (address == EXECUTE_OFFSET) {
            stage = "Execute";
        }
        
        return String.format("%s (Étape: %s, Adresse: %s)", 
            stage, 
            stage.isEmpty() ? "Inconnue" : stage, 
            hex);
    }
    
    int fin=0; //intruction fin de programme
    
    int cptASupp = 0;
    int ligneSelectionne = 0;int valeurPct=0; int valeurPrt=0;int cptASupp2=0;
    
    Color[] mesCouleurs = {
       
        new java.awt.Color(64,128+64,128+64+63),
        new java.awt.Color(64,128+64+63,64),
        new java.awt.Color(128+64,128,128+64),
        new java.awt.Color(128,128+64,128+64),
        new java.awt.Color(128+64+63,128+64,128+64),
        new java.awt.Color(128+64+63,128+64+63,64),
        new java.awt.Color(128+64+63,128,128),
        new java.awt.Color(128+64,128+64,128+64+63)};
    Ihm ihm;
    
    /** Creates new form PanelBouttons */
    public PanelBouttons(Ihm ihm) {
        initComponents();
        this.ihm=ihm;

    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JButton jButtonOneStep = new javax.swing.JButton();
        // Variables declaration - do not modify//GEN-BEGIN:variables
        javax.swing.JButton jButton3 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(250, 33));

        jButtonOneStep.setText("Pas à Pas");
        jButtonOneStep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOneStepActionPerformed(evt);
            }
        });
        add(jButtonOneStep);

        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
            add(jButton3);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOneStepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOneStepActionPerformed

        
       for(EtatPipeline ep : ihm.LCM3simulator.thePipe.getEtat()) {
           System.out.println("État du pipeline: " + formatPipelineAddress(ep.getFetchPC()));
       }
       
       valeurPrt = ihm.LCM3simulator.thePipe.getEtat()[0].getFetchPC();
       System.out.println("Adresse courante du pipeline: " + formatPipelineAddress(valeurPrt));
       if (valeurPrt==-1){
           ligneSelectionne= 0;
           valeurPct=ligneSelectionne;
       }
       else if ( valeurPrt > valeurPct )
          {valeurPct=valeurPrt;
              ligneSelectionne = valeurPrt - DECODE_OFFSET - cptASupp2;
      
       }
       else if (valeurPrt < valeurPct )
        {
           cptASupp2=1;
            ligneSelectionne = valeurPrt - ROM_BASE_ADDRESS;  // Calcul de l'offset relatif dans la ROM
            valeurPct=ligneSelectionne;
        }

        if(cptASupp -2 >= 0) {
            ihm.panelMemoires.selectionnerLigne(cptASupp - 2, mesCouleurs[(cptASupp - 2) % 8]);
            cptASupp++;
            cptASupp2++;
        }
        
        if(ihm.enSim==Ihm.ENOK){
            ihm.LCM3simulator.oneStep();
            ihm.panelRAM.aff(ihm.LCM3simulator);
            ihm.panelPipeline.disp(ihm.LCM3simulator.thePipe);
            if (ihm.panelAnim != null) {
                ihm.panelAnim.disp(ihm.LCM3simulator.thePipe);
            }
            ihm.panelFlags.affFlags(ihm.LCM3simulator.getFlagN(),
                    ihm.LCM3simulator.getFlagZ(), ihm.LCM3simulator.getFlagV()
                    , ihm.LCM3simulator.getFlagC());
            for(Modification m : ihm.LCM3simulator.modifs.getCurModifs()){
                if(m.getType()==Modification.REG){
                    ihm.panelRegistres.setModifReg(m.getLoc(),m.getVal());
                }
                else
                if(m.getType()==Modification.PC){
                    ihm.panelRegistres.setModifPC(m.getVal());
                }
                else
                if(m.getType()==Modification.RAM){
                    ihm.panelRAM.affRouge(m.getLoc(), m.getVal());
                    ihm.panelRegistres.setModifPC(m.getVal());
                }

            }
             
            ihm.LCM3simulator.modifs.next();
              
            
            
        }

    }//GEN-LAST:event_jButtonOneStepActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Appel à reset() au lieu de resetVar() pour ne pas réinitialiser la RAM
        ihm.LCM3simulator.reset();
     
        
        ihm.initAff();

    }//GEN-LAST:event_jButton3ActionPerformed


    // End of variables declaration//GEN-END:variables
    
   

    public void setFin(int fin) {
        this.fin = fin;
    }
    
    public void stop(){
        this.cptASupp = cptASupp -5;
    }
    public void bcle(int delta){
        this.cptASupp = cptASupp + delta - 1;
    }
    public void initAff() {
        this.cptASupp = 0;
        this.cptASupp2 =0;
        this.ligneSelectionne = 0;
        this.valeurPct=0;
        this.valeurPrt=0;
    }

    
}
