/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelDialog.java
 *  azerty
 * Created on 13 févr. 2010, 01:12:20
 * @author  Betty && Samira
 */

package ensea.simulateurSTM32.ihm.Panel;

import javax.swing.JTextPane;
import java.awt.*;
import java.util.HashSet;
import java.util.Set;

/**
 * Permet l'état du simulateur après analyse des instructions - Compilation -Assemblage
 * @author Pingoo
 */


public class PanelDialog extends javax.swing.JPanel {

    /** Creates new form PanelDialog */
    public PanelDialog() {
        initComponents();
        reportedLines = new HashSet<>();
    }

    // SOupe Maison
    public String getText() {
        return jTextPane1.getText();
    }

    public void setText(String text) {
        this.jTextPane1.setText(text);
    }

    private Set<Integer> reportedLines;

    // Append an error message only if that line hasn't been reported yet
    public void appendErrorForLine(int line, String errStr) {
        if (!reportedLines.contains(line)) {
            this.jTextPane1.setText(this.jTextPane1.getText() + errStr);
            reportedLines.add(line);
        }
    }

    public void clearReportedLines() {
        reportedLines.clear();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        // Variables declaration - do not modify//GEN-BEGIN:variables
        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setBackground(new java.awt.Color(240, 240, 240));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        setMinimumSize(new java.awt.Dimension(200, 100));
        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setFont(new java.awt.Font("Comic Sans MS", Font.PLAIN, 11)); // NOI18N
        jScrollPane1.setInheritsPopupMenu(true);
        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 0), 2));
        jScrollPane1.setBackground(new java.awt.Color(255, 51, 51));

        jTextPane1.setAlignmentX(10.0F);
        jTextPane1.setMinimumSize(new java.awt.Dimension(20, 80));
        jTextPane1.setPreferredSize(new java.awt.Dimension(20, 160));
        jScrollPane1.setViewportView(jTextPane1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables

    public JTextPane getjTextPane1() {
        return jTextPane1;
    }



}