/* To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelEdition.java
 *
 * Created on 11 fÃ©vr. 2010, 22:41:55
 */

package ensea.simulateurSTM32.ihm.Panel;
import ensea.simulateurSTM32.LCM3.Memory;
import ensea.simulateurSTM32.LCM3.RAM;
import ensea.simulateurSTM32.LCM3.SimLCM3;
import ensea.simulateurSTM32.ihm.Ihm;

import java.awt.*;

/**
 *
 * Permet l'affichage de la RAM -Permettra Ã©galement d'Ã©diter la RAM
 */
public class PanelRAM extends javax.swing.JPanel {

    Ihm ihm;

    /** Creates new form PanelEdition */
    public PanelRAM(Ihm ihm) {
        initComponents();
        this.initComponents2();
        this.ihm=ihm;

        // Listener pour mettre à jour la RAM lors de l'édition
        jTableRAM.addPropertyChangeListener("tableCellEditor", evt -> {
            if (!jTableRAM.isEditing()) {
                // L'édition vient de se terminer
                syncTableColumns();
                if (ihm.LCM3simulator != null) {
                    commitToSimulator(ihm.LCM3simulator);
                }
            }
        });
    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        // Variables declaration - do not modify//GEN-BEGIN:variables
        javax.swing.JScrollPane jScrollPaneRAM = new javax.swing.JScrollPane();
        jTableRAM = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    setPreferredSize(new java.awt.Dimension(180, 234));
    setLayout(new java.awt.BorderLayout());

        jTableRAM.setBackground(new java.awt.Color(204, 255, 153));
        jTableRAM.setFont(new java.awt.Font("Courier New", Font.PLAIN, 13)); // NOI18N
        jTableRAM.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null},
                        {null, null, null},
                        {null, null, null},
                        {null, null, null},
                        {null, null, null},
                        {null, null, null},
                        {null, null, null},
                        {null, null, null},
                        {null, null, null},
                        {null, null, null},
                        {null, null, null}
                },
                new String [] {
                        "Adresse", "int", "hex"
                }
        ) {
            final Class[] types = new Class [] {
                    java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            // only allow editing of int (1) and hex (2) columns
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return (columnIndex == 1 || columnIndex == 2);
            }
        });
        jTableRAM.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTableRAM.setSelectionForeground(new java.awt.Color(255, 51, 0));
        jTableRAM.getTableHeader().setReorderingAllowed(false);
        jScrollPaneRAM.setViewportView(jTableRAM);

    // Ajouter le scroll pane contenant la table au centre
    add(jScrollPaneRAM, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    private javax.swing.JTable jTableRAM;
    // End of variables declaration//GEN-END:variables

    private void initComponents2() {
        javax.swing.table.TableColumnModel colModel = jTableRAM.getColumnModel();

        colModel.getColumn(1).setPreferredWidth(40);
        colModel.getColumn(1).setMaxWidth(60);

        colModel.getColumn(0).setPreferredWidth(90);
        colModel.getColumn(2).setPreferredWidth(90);

        javax.swing.JButton resetRAMButton = new javax.swing.JButton("Reset RAM");
        resetRAMButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                if (ihm.LCM3simulator != null) {
                    ihm.LCM3simulator.resetRAM();
                    aff(ihm.LCM3simulator);
                }
            }
        });

        add(resetRAMButton, java.awt.BorderLayout.SOUTH);
    }

    private int parseHex(String s){
        s = s.trim();
        if(s.startsWith("0x")||s.startsWith("0X")) s = s.substring(2);
        return (int)Long.parseLong(s,16);
    }
    private int parseDec(String s){
        s = s.trim();
        return Integer.parseInt(s);
    }
    private String toHexPrefixed(int v){
        Memory mem=new Memory(4,4);
        return "0x"+mem.inHexa(v,8);
    }
    public void dispVal(int i, int val){
        this.jTableRAM.setValueAt(String.valueOf(val),i,1);
        this.jTableRAM.setValueAt(toHexPrefixed(val),i,2);
    }
    public void dispAdr(int i, int adr){
        Memory mem=new Memory(4,4);
        String buf="0x";
        buf=buf.concat(mem.inHexa(adr,8));
        this.jTableRAM.setValueAt(buf,i,0);
    }


    public void initAff(SimLCM3 LCM3simulator) {
        int i,val,adr;
        this.jTableRAM.setForeground(Color.blue);
        for(i=0;i<10;i++){
            adr=RAM.BASERAM+i*4;
            val=LCM3simulator.getTheRAM().readW(RAM.BASERAM+i*4);
            dispAdr(i,adr);
            dispVal(i,val);
        }
    }
    public void aff(SimLCM3 LCM3simulator) {
        int i,val,adr;
        this.jTableRAM.setForeground(Color.black);
        for(i=0;i<10;i++){
            adr=RAM.BASERAM+i*4;
            val=LCM3simulator.getTheRAM().readW(RAM.BASERAM+i*4);
            dispAdr(i,adr);
            dispVal(i,val);
        }
    }

    public void affRouge(int adr, int val) {
        int i;
        i=(adr-RAM.BASERAM)/4;
        this.jTableRAM.setForeground(Color.red);
        dispAdr(i,adr);
        dispVal(i,val);
    }

    // Read user edits from the table and write them into the simulator RAM.
    public void commitToSimulator(SimLCM3 sim){
        if (sim == null) {
            System.out.println("Warning: Cannot commit to null simulator");
            return;
        }
        
        // user may still be editing
        if(this.jTableRAM.isEditing()){
            try{ 
                this.jTableRAM.getCellEditor().stopCellEditing(); 
            } catch(Exception ex){
                System.out.println("Warning: Could not stop cell editing: " + ex.getMessage());
            }
        }
        
        int rows = this.jTableRAM.getRowCount();
        for(int i=0;i<rows;i++){
            Object intObj = jTableRAM.getValueAt(i,1);
            Object hexObj = jTableRAM.getValueAt(i,2);
            int adr = RAM.BASERAM + i*4;
            Integer value = null;

            boolean b1 = hexObj != null && !hexObj.toString().trim().isEmpty();
            boolean b2 = intObj != null && !intObj.toString().trim().isEmpty();
            try{
                if(b2){
                    // decimal
                    value = parseDec(intObj.toString());
                }else {
                    if (!b1) {
                    } else {
                        value = parseHex(hexObj.toString());
                    }
                }
            }catch(NumberFormatException ex){
                // hex
                try{
                    if(b2) {
                        value = parseHex(intObj.toString());
                    } else value = parseDec(hexObj.toString());
                }catch(NumberFormatException ex2){
                    // invalid input -> ignore and continue
                }
            }
            if(value!=null){
                System.out.println("PanelRAM: writing RAM at 0x"+Integer.toHexString(adr)+" = "+value);
                sim.initValRAM(adr, value);
            }
        }
    }

    // synchronize hex/dec columns in table
    public void syncTableColumns(){
        new Memory(4, 4);
        if(this.jTableRAM.isEditing()){
            try{ this.jTableRAM.getCellEditor().stopCellEditing(); }catch(Exception _){}
        }
        int rows = this.jTableRAM.getRowCount();
        for(int i=0;i<rows;i++){
            Object intObj = jTableRAM.getValueAt(i,1);
            Object hexObj = jTableRAM.getValueAt(i,2);
            try{
                if(intObj!=null && !intObj.toString().trim().isEmpty()){
                    int v = parseDec(intObj.toString());
                    jTableRAM.setValueAt(toHexPrefixed(v), i, 2);
                }else if(hexObj!=null && !hexObj.toString().trim().isEmpty()){
                    int v = parseHex(hexObj.toString());
                    jTableRAM.setValueAt(String.valueOf(v), i, 1);
                }
            }catch(NumberFormatException ex){
                // ignore malformed cell
            }
        }
    }
}