/*
 * PanelBouttons.java
 */

/* *    Choix de l'execution PasàPas -Reset - 
 * @author  Guillaume - Vincent
 */

package ensea.simulateurSTM32.ihm.Panel;

import ensea.simulateurSTM32.LCM3.Modification;
import ensea.simulateurSTM32.ihm.Ihm;
import java.awt.Color;

import java.util.ArrayList;
import java.util.List;
import ensea.simulateurSTM32.LCM3.EtatPipeline;
import ensea.simulateurSTM32.LCM3.Memory;
import ensea.simulateurSTM32.LCM3.Pipeline;



/**
Choix de l'execution Pas à Pas -Reset - 
 */


public class PanelBouttons extends javax.swing.JPanel {
  
    int checkstop=0;  //interruption volontaire de programme
    int fin=0; //intruction fin de programme
    
    int cptASupp = 0;
    int ligneSelectionne = 0;int valeurPct=0; int valeurPrt=0;int cptASupp2=0;
    
    
   
     
    
        
       
        Memory mem=new Memory(4,4);
//     e = p.getEtat()[2];
    
    Color[] mesCouleurs = {
       
        new java.awt.Color(64,128+64,128+64+63),
        new java.awt.Color(64,128+64+63,64),
        new java.awt.Color(128+64,128,128+64),
        new java.awt.Color(128,128+64,128+64),
        new java.awt.Color(128+64+63,128+64,128+64),
        new java.awt.Color(128+64+63,128+64+63,64),
        new java.awt.Color(128+64+63,128,128),
        new java.awt.Color(128+64,128+64,128+64+63)};
    Ihm ihm;
    
    /** Creates new form PanelBouttons */
    public PanelBouttons(Ihm ihm) {
        initComponents();
        this.ihm=ihm;

    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonOneStep = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(250, 33));

        jButtonOneStep.setText("Pas à Pas");
        jButtonOneStep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOneStepActionPerformed(evt);
            }
        });
        add(jButtonOneStep);

        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOneStepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOneStepActionPerformed
        /** 
         * LE GROS BOULET
         * Déselection des lignes de la jTableROM
        ihm.panelMemoires.getjTableROM().getSelectionModel().clearSelection();
        // Sélection de la ligne de code executé par le microproc dans la jTableROM
        ihm.panelMemoires.getjTableROM().getSelectionModel().addSelectionInterval(cptASupp, cptASupp);
         ihm.panelMemoires.getjTableROM().setSelectionBackground(mesCouleurs[cptASupp%3]);
                 cptASupp++;**/
        
  //  EtatPipeline e;
    // e=p.getEtat()[2];
      
  //System.out.println(e.getFetchPC()+" "+cptASupp);
   // System.out.println(e);
        
       for(EtatPipeline ep : ihm.LCM3simulator.thePipe.getEtat()) {
           System.out.println("Etat "+ep.getFetchPC());
           
       }
       
       valeurPrt= ihm.LCM3simulator.thePipe.getEtat()[0].getFetchPC();
       System.out.println("valeurPrt"+valeurPrt);
       if (valeurPrt==-1){
           ligneSelectionne= 0;
           valeurPct=ligneSelectionne;
           System.out.println("ligneSelectionne"+ligneSelectionne);
       }
       else if (valeurPrt!=-1 && valeurPrt > valeurPct ) 
          {valeurPct=valeurPrt;
              ligneSelectionne= valeurPrt-134217726-cptASupp2;
      
       }
       else if (valeurPrt!=-1 && valeurPrt < valeurPct ) 
        {System.out.println ("inversement"+valeurPct+"valeurPrt"+ valeurPrt);
           cptASupp2=1;
            ligneSelectionne = valeurPrt- 134217728;
            valeurPct=ligneSelectionne;
        }
      /** int ligneSelectionne = 0;
       if(ihm.LCM3simulator.thePipe.getEtat()[2].getFetchPC() < cptASupp) cptASupp = 0;
       if(ihm.LCM3simulator.thePipe.getEtat()[0].getFetchPC() != -1) {
           ligneSelectionne = ihm.LCM3simulator.thePipe.getEtat()[0].getFetchPC() -((ihm.LCM3simulator.thePipe.getEtat()[0].getFetchPC()-1)%(ihm.LCM3simulator.thePipe.getEtat()[0].getFetchPC()));
           cptASupp++;
       }
        System.out.println("Ligne Supp"+ligneSelectionne);**/
      
      //  System.out.println("je veux afficher"+etatPipelines[1].getFetchPC());
        if(cptASupp -2 >= 0) 
        ihm.panelMemoires.selectionnerLigne(cptASupp-2,mesCouleurs[(cptASupp-2)%8]); 
        cptASupp++;
        cptASupp2++;
        //e.getFetchPC()-0x08000000
          
        /**(mem.inHexa(e.getFetchPC(),8)**/
        
        if(ihm.enSim==Ihm.ENOK){
             System.out.println("salut");
            ihm.LCM3simulator.oneStep();
            ihm.panelRAM.aff(ihm.LCM3simulator);
            ihm.panelPipeline.disp(ihm.LCM3simulator.thePipe);
            ihm.panelFlags.affFlags(ihm.LCM3simulator.getFlagN(),
                    ihm.LCM3simulator.getFlagZ(), ihm.LCM3simulator.getFlagV()
                    , ihm.LCM3simulator.getFlagC());
            for(Modification m : ihm.LCM3simulator.modifs.getCurModifs()){
                if(m.getType()==Modification.REG){
                    ihm.panelRegistres.setModifReg(m.getLoc(),m.getVal());
                }
                else
                if(m.getType()==Modification.PC){
                    ihm.panelRegistres.setModifPC(m.getVal());
                }
                else
                if(m.getType()==Modification.RAM){
                    ihm.panelRAM.affRouge(m.getLoc(), m.getVal());
                    ihm.panelRegistres.setModifPC(m.getVal());
                }

            }
             
            ihm.LCM3simulator.modifs.next();
              
            
            
        }
      /*  if (fin==0) ihm.simmanager.executepasapas(ihm);*/

    }//GEN-LAST:event_jButtonOneStepActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ihm.LCM3simulator.resetVar();
     
        
        ihm.initAff();
    //    ihm.simmanager.reset(ihm);

    }//GEN-LAST:event_jButton3ActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonOneStep;
    // End of variables declaration//GEN-END:variables
    
   

    public void setFin(int fin) {
        this.fin = fin;
    }
    
    public void stop(){
        this.cptASupp = cptASupp -5;
    }
    public void bcle(int delta){
        this.cptASupp = cptASupp + delta - 1;
    }
    public void initAff() {
        this.cptASupp = 0;
        this.cptASupp2 =0;this.ligneSelectionne = 0;this.valeurPct=0;this.valeurPrt=0;this.cptASupp2=0;
    }
    



    



}
