/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelCode.java
 *
 *
 */

package ensea.simulateurSTM32.ihm.Panel;
import ensea.simulateurSTM32.ihm.Ihm;

/*
   Fenêtre d'édition
  @author  Vincent-Guillaume
 */

import ensea.simulateurSTM32.parseur.Etiquette;
import ensea.simulateurSTM32.parseur.Instruction;
import ensea.simulateurSTM32.parseur.Parseur;
import ensea.simulateurSTM32.simulateurstm32.MainFrame;

import java.util.ArrayList;
import javax.swing.JTextPane;

/*
    Fenêtre d'édition des instructions
 */

public class PanelCode extends javax.swing.JPanel {
     Ihm ihm;
     protected ArrayList<Instruction> listeCommandes;
     private LineNumbering lineNumbers; // ajout ligne de numérotation

    /* Creates new form PanelCode */
    public PanelCode(Ihm ihm) {
        initComponents();
        listeCommandes=new ArrayList<>();
        this.ihm=ihm;
    }


    // Soupe Maison
    public String getText() {
        return jTextPane1.getText();
    }

    public void setText(String text) {
        this.jTextPane1.setText(text);
    }


    /*This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jColorChooser2 = new javax.swing.JColorChooser();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();

        setForeground(new java.awt.Color(204, 204, 0));
        setPreferredSize(new java.awt.Dimension(315, 700));


        jButton1.setText("ASSEMBLAGE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextPane1.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jTextPane1.setMinimumSize(new java.awt.Dimension(60, 22));
        jTextPane1.setPreferredSize(new java.awt.Dimension(60, 10000));
        jScrollPane1.setViewportView(jTextPane1);


        jTextPane2.setEditable(false);
        jTextPane2.setText(" theFin : B theFin\n            MOV R0, #0\n            MOV R0, R0");
        jTextPane2.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jTextPane2.setMinimumSize(new java.awt.Dimension(60, 22));
        jTextPane2.setPreferredSize(new java.awt.Dimension(60, 10000));
        jScrollPane2.setViewportView(jTextPane2);

        // Ajout de la numérotation des lignes
        lineNumbers = new LineNumbering(jTextPane1);
        jScrollPane1.setRowHeaderView(lineNumbers);

        // Ajout d'un écouteur sur les modifications du document pour les liges
        jTextPane1.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                lineNumbers.updateLineNumbers();
            }
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                lineNumbers.updateLineNumbers();
            }
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                lineNumbers.updateLineNumbers();
            }
        });


        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(102, 102, 102))
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(278, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

   private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
    PanelCode e = this.ihm.panelcode; // Code Assembleur en Entrée
    PanelMemoires s = this.ihm.panelMemoires; // Mémoire résultant de l'asm
    PanelDialog err = this.ihm.panelDialog; // Console de Sortie Erreur

    /* Variables nécessaires pour l'assemblage */
    System.out.println("ASM GO");
    System.out.println(e.getText());
    
    this.ihm.enSim = Ihm.ENNOTOK;
    int ligne = 0;
    ArrayList<Etiquette> listeEtiquette = new ArrayList<>();
    String texteCode;
    
    texteCode = e.getText();
    texteCode = texteCode.concat("\n");
    texteCode = texteCode.concat("theFin: b theFin\n");
    texteCode = texteCode.concat("MSBAdrRAM: MOV R0,#0\n");
    texteCode = texteCode.concat("LSBAdrRAM: MOV R0,R0\n");
    
    Parseur parsEtiq = new Parseur(texteCode, err);
    boolean noASMError = true;
    
    System.out.println(this.ihm.LCM3simulator);
    this.ihm.instructionsToBeDownloaded.clear();
    this.ihm.codeToBeDownloaded.clear();
    
    // Initialiser la zone d'erreur
    err.setText("");
    err.clearReportedLines();
    
    // ===== PASSE 1 : Premier parsage pour récupérer les étiquettes =====
    while (parsEtiq.termine()) {
        String a1 = parsEtiq.obtenirMot();
        
        if (!a1.isEmpty()) {
            // Ne considérer comme étiquette que si le mot est suivi d'un ':' (tolère espaces)
            int temp = parsEtiq.indice;
            int spaces = 0;
            while (temp < parsEtiq.texte.length() && 
                   (parsEtiq.texte.charAt(temp) == ' ' || 
                    parsEtiq.texte.charAt(temp) == '\t')) {
                temp++;
                spaces++;
            }
            
            if (temp < parsEtiq.texte.length() && 
                parsEtiq.texte.charAt(temp) == ':') {
                // C'est une étiquette
                listeEtiquette.add(new Etiquette(ligne, a1));
                parsEtiq.indice = temp + 1;
                parsEtiq.colonne += a1.length() + spaces + 1;
            } else {
                // Ce n'est pas une étiquette : reculer pour que le parseur traite le mot comme instruction
                parsEtiq.indice -= a1.length();
                parsEtiq.colonne -= a1.length();
            }
        }
        
        parsEtiq.passerEspace();
        
        Instruction instrTest = parsEtiq.TypeParam();
        
        //  VÉRIFICATION CRITIQUE : marquer l'erreur mais continuer pour collecter d'autres erreurs
        if (!err.getText().isEmpty()) {
            s.setText("NO CODE");
            this.ihm.enSim = Ihm.ENNOTOK;
            noASMError = false;
            // avancer à la fin de la ligne avant de continuer
            parsEtiq.finLigne();
            continue;
        }
        
        if (instrTest != null) {
            ligne++;
        }
        
        parsEtiq.finLigne();
        
        // Vérifier après finLigne() aussi
        if (!err.getText().isEmpty()) {
            s.setText("NO CODE");
            this.ihm.enSim = Ihm.ENNOTOK;
            noASMError = false;
            // continuer la passe pour collecter d'autres erreurs
        }
    }
    
    // ===== PASSE 2 : Second parsage pour récupérer les instructions =====
    ligne = 0;
    Parseur parsInstr = new Parseur(texteCode, err);
    Instruction reconnue, identifiee = null;
    StringBuilder binaire = new StringBuilder();
    
    while (parsInstr.termine()) {
        /* Sauter l'étiquette si présente (mot suivi de ':') */
        String premier = parsInstr.obtenirMot();
        
        if (!premier.isEmpty()) {
            int tmp = parsInstr.indice;
            int sp = 0;
            while (tmp < parsInstr.texte.length() && 
                   (parsInstr.texte.charAt(tmp) == ' ' || 
                    parsInstr.texte.charAt(tmp) == '\t')) {
                tmp++;
                sp++;
            }
            
            if (tmp < parsInstr.texte.length() && 
                parsInstr.texte.charAt(tmp) == ':') {
                // Étiquette : avancer après ':'
                parsInstr.indice = tmp + 1;
                parsInstr.colonne += premier.length() + sp + 1;
            } else {
                // Pas d'étiquette : revenir en arrière pour que TypeParam lise l'instruction
                parsInstr.indice -= premier.length();
                parsInstr.colonne -= premier.length();
            }
        }
        
        parsInstr.passerEspace();
        
        /* Prendre l'instruction */
        reconnue = parsInstr.TypeParam();
        
        //  VÉRIFICATION : marquer l'erreur mais continuer pour collecter d'autres erreurs
        if (!err.getText().isEmpty()) {
            s.setText("NO CODE");
            this.ihm.enSim = Ihm.ENNOTOK;
            noASMError = false;
            // avancer à la fin de la ligne avant de continuer
            parsInstr.finLigne();
            continue;
        }
        
        if (reconnue != null) {
            ligne++;
            identifiee = null;
            
            for (Instruction i : MainFrame.assPrincipal.getListeCommandes()) {
                if (i.compInstr(reconnue)) {
                    identifiee = i;
                    break;
                }
            }
            
            System.out.println("DEBUG PanelCode: identifiee=" + (identifiee == null ? "NULL (aucun template trouvé !)" : identifiee.getNom()));
            if (identifiee != null) {
                reconnue.charger(identifiee);
                System.out.println("DEBUG PanelCode: après charger(), params (" + reconnue.getListeParams().size() + "):");
                for (int _pi = 0; _pi < reconnue.getListeParams().size(); _pi++) {
                    ensea.simulateurSTM32.parseur.Instruction.Mot _pm = reconnue.getListeParams().get(_pi);
                    System.out.println("  Param[" + _pi + "] type=" + _pm.getClass().getSimpleName() + " ordre=" + _pm.getOrdre() + " valBin='" + _pm.getValBin() + "'");
                }
                try {
                    String codeBin = reconnue.genererBin(listeEtiquette, ligne);
                    System.out.println("DEBUG PanelCode: codeBin généré='" + codeBin + "'");
                    binaire.append(codeBin).append("\n");
                    reconnue.setLine(ligne);
                    this.ihm.instructionsToBeDownloaded.add(reconnue);
                    this.ihm.codeToBeDownloaded.add(codeBin);
                } catch (Exception ex) {
                    // append instead of overwrite, marquer erreur et continuer
                    err.setText(err.getText() + "Ligne " + ligne + ": Erreur de génération (" + ex.getMessage() + ")\n");
                    s.setText("NO CODE");
                    this.ihm.enSim = Ihm.ENNOTOK;
                    noASMError = false;
                    parsInstr.finLigne();
                    continue;
                }
            } else {
                // Instruction non reconnue: append error, mark and continue
                err.setText(err.getText() + "Ligne " + ligne + " : Instruction non reconnue ou syntaxe incorrecte\n");
                noASMError = false;
                s.setText("NO CODE");
                this.ihm.enSim = Ihm.ENNOTOK;
                parsInstr.finLigne();
                continue;
            }
        }
        
        parsInstr.finLigne();
        
        // *** VÉRIFICATION après finLigne ***
        if (!err.getText().isEmpty()) {
            s.setText("NO CODE");
            this.ihm.enSim = Ihm.ENNOTOK;
            return;
        }
    }
    
    // RÉSULTAT FINAL
    if (noASMError && err.getText().isEmpty()) {
        s.setText(binaire.toString());
        
        if (checkValParam()) {
            err.setText("Code assembleur correct: SIMULATION POSSIBLE");
            this.ihm.enSim = Ihm.ENOK;
            this.ihm.panelRegistres.formatAff = 0;
            
            // Utiliser reset() au lieu de reset2() pour préserver la RAM saisie par l'utilisateur
            this.ihm.LCM3simulator.reset();
            this.ihm.LCM3simulator.download(
                this.ihm.instructionsToBeDownloaded,
                this.ihm.codeToBeDownloaded
            );
            this.ihm.panelMemoires.downloadCode(this.ihm.LCM3simulator);
            ihm.LCM3simulator.resetVar();
            this.ihm.panelRAM.syncTableColumns();
            this.ihm.panelRAM.commitToSimulator(this.ihm.LCM3simulator);
            ihm.initAff();
        } else {
            this.ihm.LCM3simulator.reset();
            this.ihm.enSim = Ihm.ENNOTOK;
            err.setText("Erreur: valeur erronée de paramètre(s)");
            System.out.println("simulation impossible");
        }
    } else {
        // S'assurer que la zone d'erreur contient quelque chose
        if (err.getText().isEmpty()) {
            err.setText("Erreur d'assemblage détectée");
        }
        s.setText("NO CODE");
        this.ihm.enSim = Ihm.ENNOTOK;
    }
}


    private int getCodeInInt(String binaryCode){
        int val=0,i,w=0x8000;
        char bit;
        for(i=0;i<16;i++){
            bit=binaryCode.charAt(i);
            if(bit=='1')
                val+=w;
            w=w>>1;
        }
        return val;
    }
    public boolean checkValParam() {
        int n=0;

        for(Instruction i : this.ihm.instructionsToBeDownloaded){
            System.out.println("instruction:"+i.getNom()+
                    "=>"+this.ihm.codeToBeDownloaded.get(n)+
                    "="+getCodeInInt(this.ihm.codeToBeDownloaded.get(n)));
            if(!i.checkValParam()){
                System.out.println("instruction:"+i.getNom()+
                        " ERREUR pour val instruction n°"+i.getLine());
                return false;
            }
            System.out.println("instruction:"+i.getNom()+"OK pour val");
            n++;

        }
        return true;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JColorChooser jColorChooser2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    // End of variables declaration//GEN-END:variables

    public JTextPane getjTextPane1() {
        return jTextPane1;
    }



}
