/*
 * Ihm.java
 *
 *
 * @author  Betty && Samira
 */

package ensea.simulateurSTM32.ihm;


import ensea.simulateurSTM32.LCM3.SimLCM3;
import java.io.*;
import javax.swing.*; 
import javax.swing.JFileChooser;

//import Simulateur.Kernel.SimManager;
import ensea.simulateurSTM32.ihm.Panel.PanelDialog;
import ensea.simulateurSTM32.ihm.Panel.PanelPipeline;
import ensea.simulateurSTM32.ihm.Panel.PanelFlags;
import ensea.simulateurSTM32.ihm.Panel.PanelRAM;
import ensea.simulateurSTM32.ihm.Panel.PanelBouttons;
import ensea.simulateurSTM32.ihm.Panel.PanelMemoires;
import ensea.simulateurSTM32.ihm.Panel.PanelRegistres;
import ensea.simulateurSTM32.ihm.Panel.PanelCode;
import ensea.simulateurSTM32.parseur.Instruction;
import java.util.ArrayList;
/**
 *
 * @author  Betty &&Samira
 */
public class Ihm extends javax.swing.JFrame {
    
    public int adresseDebutProgramme;
    public int adresseFinProgramme;
    
    
    
    public PanelBouttons panelBouttons;
    public PanelMemoires panelMemoires;
    public PanelRegistres panelRegistres;
//    public SimManager simmanager;
    public PanelFlags panelFlags;
    public PanelPipeline panelPipeline;
    public PanelDialog panelDialog;
    public PanelRAM panelRAM;
    public PanelCode panelcode;

    //added by LM BEGIN
    public ArrayList<Instruction> instructionsToBeDownloaded;
    public ArrayList<String> codeToBeDownloaded;
    public SimLCM3 LCM3simulator;
    public int enSim=0;
    public static final int ENOK = 1;
    public static final int ENNOTOK = 0;
    //added by LM END


    /** Creates new form Ihm */
    public Ihm() {
        setTitle("Simulation Microprocesseur");


        //demarage du noyau
        instructionsToBeDownloaded=new ArrayList();
        codeToBeDownloaded=new ArrayList();
        LCM3simulator=new SimLCM3();
        LCM3simulator.reset();        
        //instanciation des divers Panels
        panelBouttons = new PanelBouttons(this);
        panelMemoires = new PanelMemoires(); // new PanelMemoires(simmanager.getRom());
   
        panelRegistres = new PanelRegistres(); // new PanelRegistres(simmanager.getRegistres(),simmanager.getFetch());
        panelRAM=new PanelRAM(this);
        panelPipeline=new PanelPipeline(this);
        panelFlags= new PanelFlags(this);
        panelDialog=new PanelDialog();
        panelcode= new PanelCode(this);


        
        adresseDebutProgramme=0x20000;

        initComponents();
        this.initAff();



    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LCM3 : Le simulateur made in ENSEA                                                                                         VIVE LA VOILE !!                                                                                       ");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1100, 700));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        miseEnPage();

        jMenu1.setText("Fichier");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Charger code");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setText("Enregistrer code ");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Quitter");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edition");

        jMenuItem4.setText("Auteurs");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0);
}//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:

        JFileChooser chooser = new JFileChooser();//création dun nouveau filechosser
       
        chooser.showDialog(null,"Enregistrer");


        File fichier =chooser.getSelectedFile();
        String chaine= panelcode.getjTextPane1().getText();


        //ecriture du fichier texte
        try {
            FileWriter fw = new FileWriter(fichier);
            BufferedWriter bw = new BufferedWriter(fw);
            PrintWriter fichierSortie = new PrintWriter(bw);


            fichierSortie.println(chaine);
            fichierSortie.close();
            System.out.println("Le fichier a été crée");

            panelDialog.getjTextPane1().setText("Enregistrement du fichier "+fichier.getName());

        }

        catch (Exception e){
            System.out.println(e.toString());
        }




    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed


        JFileChooser chooser = new JFileChooser();//création dun nouveau filechosser
        chooser.showOpenDialog(null); //affiche la boite de dialogue
        File fichier =chooser.getSelectedFile();
        String chaine="";

        //lecture du fichier texte
        try{
            InputStream ips=new FileInputStream(fichier);
            InputStreamReader ipsr=new InputStreamReader(ips);
            BufferedReader br=new BufferedReader(ipsr);
            String ligne;
            while ((ligne=br.readLine())!=null){
                chaine=chaine+ligne+'\n';
            }
            br.close();
            
            panelDialog.getjTextPane1().setText("Chargement du fichier "+fichier.getName());

        }

        catch (Exception e){
            System.out.println(e.toString());
        }

        panelcode.getjTextPane1().setText(chaine);

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
           JOptionPane d= new JOptionPane();   //permet de creer une fenetre auteurs
           d.showMessageDialog(this,
                "2011-2012: Guillaume CHAIGNON & Vincent PINGARD \n2010-2011: Hadrian OVAZZA & Louis ROLLAND \n2009-2010: Betty BASTAREAUD & Samira ROCHDI",
                
                " Auteurs",
                JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
// TODO add your handling code here:
}//GEN-LAST:event_formComponentResized
    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JMenu jMenu1;
    javax.swing.JMenu jMenu2;
    javax.swing.JMenuBar jMenuBar1;
    javax.swing.JMenuItem jMenuItem1;
    javax.swing.JMenuItem jMenuItem2;
    javax.swing.JMenuItem jMenuItem4;
    javax.swing.JMenuItem jMenuItem5;
    // End of variables declaration//GEN-END:variables


    // mise en place de l'agencement des différents panels
    private void miseEnPage(){

        java.awt.GridBagConstraints gridBagConstraints;

        panelBouttons.setName("Controle");
        gridBagConstraints = new java.awt.GridBagConstraints();
        panelBouttons.setPreferredSize(new java.awt.Dimension(320, 40));
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.weightx = 0.5;
        getContentPane().add(panelBouttons,gridBagConstraints);

        panelRegistres.setMinimumSize(new java.awt.Dimension(160, 142));
        panelRegistres.setName("registres");
        panelRegistres.setPreferredSize(new java.awt.Dimension(270, 150));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipady = 10;
        getContentPane().add(panelRegistres, gridBagConstraints);


        panelFlags.setName("flag");
        gridBagConstraints = new java.awt.GridBagConstraints();
        panelFlags.setPreferredSize(new java.awt.Dimension(240, 120));
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        getContentPane().add(panelFlags, gridBagConstraints);

        panelMemoires.setName("Memoires");
        gridBagConstraints = new java.awt.GridBagConstraints();
         panelMemoires.setPreferredSize(new java.awt.Dimension(350, 250));
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        //gridBagConstraints.gridwidth = 2;
        getContentPane().add(panelMemoires, gridBagConstraints);


        panelPipeline.setName("Pipeline");
        gridBagConstraints = new java.awt.GridBagConstraints();
        panelPipeline.setPreferredSize(new java.awt.Dimension(350, 210));
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy =2;
        gridBagConstraints.gridheight = 2;
        getContentPane().add(panelPipeline, gridBagConstraints);

        panelRAM.setName("Edit");

        panelRAM.setMinimumSize(new java.awt.Dimension(160, 142));
        panelRAM.setName("edit");
        panelRAM.setPreferredSize(new java.awt.Dimension(270, 200));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy =3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 3;
        getContentPane().add(panelRAM, gridBagConstraints);
        
        panelDialog.setName("Dialog");
        panelDialog.setMinimumSize(new java.awt.Dimension(160, 142));
        panelDialog.setPreferredSize(new java.awt.Dimension(380, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();

        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy =4;
        gridBagConstraints.gridwidth = 2;
        getContentPane().add(panelDialog, gridBagConstraints);


        panelcode.setMinimumSize(new java.awt.Dimension(160, 142));
        panelcode.setName("code");
        panelcode.setPreferredSize(new java.awt.Dimension(380, 450));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy =0;
        gridBagConstraints.gridwidth =2;
        gridBagConstraints.gridheight =4;  
        getContentPane().add(panelcode, gridBagConstraints);


  
    }
    public void initAff(){
        panelRegistres.initAff();
        panelRAM.initAff(this.LCM3simulator);
        panelPipeline.disp(this.LCM3simulator.thePipe);
        panelFlags.affFlags(0, 0, 0, 0);
        panelBouttons.initAff();
        panelMemoires.initAff();
        System.out.println("vvvv");
        
    }
 
}
