/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelCode.java
 *
 * 
 */

package ensea.simulateurSTM32.ihm.Panel;
import ensea.simulateurSTM32.ihm.Ihm;
/**
 *  Fenêtre d'édition
 * @author  Vincent-Guillaume
 */

import ensea.simulateurSTM32.parseur.Etiquette;
import ensea.simulateurSTM32.parseur.Instruction;
import ensea.simulateurSTM32.parseur.Parseur;
import ensea.simulateurSTM32.simulateurstm32.MainFrame;
import java.io.*;
import java.util.ArrayList;
import javax.swing.JTextPane;

/**
    Fenêtre d'édition des instructions 
 */ 

public class PanelCode extends javax.swing.JPanel {
     Ihm ihm;
     int pc=0;
     protected ArrayList<Instruction> listeCommandes;
    /** Creates new form PanelCode */
    public PanelCode(Ihm ihm) {
        initComponents();
        listeCommandes=new ArrayList();
        this.ihm=ihm;
    }

    
    // Soupe Maison
    public String getText() {
        return jTextPane1.getText();
    }
    
    public void setText(String text) {
        this.jTextPane1.setText(text);
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jColorChooser2 = new javax.swing.JColorChooser();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setForeground(new java.awt.Color(204, 204, 0));
        setPreferredSize(new java.awt.Dimension(315, 700));

        jButton1.setText("ASSEMBLAGE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextPane1.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jTextPane1.setMinimumSize(new java.awt.Dimension(104, 22));
        jTextPane1.setPreferredSize(new java.awt.Dimension(100, 10000));
        jScrollPane1.setViewportView(jTextPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(273, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        PanelCode e = this.ihm.panelcode; // Code Assembleur en Entrée
        PanelMemoires s = this.ihm.panelMemoires;//memoire resultant de l'asm
        PanelDialog err = this.ihm.panelDialog; // Console de Sortie Erreur
        
        /* Variables nécessaire pour l'assemblage */
        /*
         * int ligne=0;
        ArrayList<Etiquette> listeEtiquette=new ArrayList();
        err.setText("");
        s.setText("");
        Parseur parsEtiq=new Parseur(e.getText(),err);
         * */
         
        System.out.println("ASM GO");
        System.out.println(e.getText());
        this.ihm.enSim=Ihm.ENNOTOK;
        //this.ihm.panelMemoires.modifyROM();
        //Variables nécessaires pour l'assemblage 
	int ligne=0;
	ArrayList<Etiquette> listeEtiquette=new ArrayList();
	//err.setText("Messages d'erreurs");
	//s.setText("Code Binaire");
        String texteCode=new String("");
        texteCode=e.getText();
        texteCode=texteCode.concat("\n");
        texteCode=texteCode.concat("theFin b theFin\n");
        texteCode=texteCode.concat("MSBAdrRAM MOV R0,#0\n");
        texteCode=texteCode.concat("LSBAdrRAM MOV R0,R0\n");
	//Parseur parsEtiq=new Parseur(e.getText(),err);
        Parseur parsEtiq=new Parseur(texteCode,err);
        //added by LM BEGIN
        boolean noASMError=true;
        System.out.println(this.ihm.LCM3simulator);
        this.ihm.instructionsToBeDownloaded.clear();
        this.ihm.codeToBeDownloaded.clear();
        //added by LM END
        // Premier parsage de la zone de texte pour récupérer les etiquettes 
        while(!parsEtiq.termine()){
                String a1=parsEtiq.obtenirMot();
                if(!a1.equals("")){
                        listeEtiquette.add(new Etiquette(ligne, a1));
                }
                parsEtiq.passerEspace();
                if(parsEtiq.TypeParam()!=null)
                        ligne++;
                parsEtiq.finLigne();
        }
       

        ligne++;
        
        err.setText("");
        if(err.getText().equals(""))
        {
                ligne=0;
                Parseur parsInstr=new Parseur(texteCode,err);
                Instruction reconnue,identifiee=null;
                String binaire="";
                noASMError=true;

                /* Second parsage de la zone de texte pour récupérer les instructions */
                while(!parsInstr.termine()){
                        /* Sauter l'étiquette */
                        parsInstr.obtenirMot();
                        parsInstr.passerEspace();



                        /* Prendre l'instruction */
                        if((reconnue=parsInstr.TypeParam())!=null)
                        {
                                ligne++;
                                identifiee=null;
  
                                for(Instruction i : MainFrame.assPrincipal.getListeCommandes())
                                {
                                        if(i.compInstr(reconnue))
                                        {
                                        identifiee=i;
                                        }
                                }
                                if(identifiee!=null)
                                {
                                        reconnue.charger(identifiee);
                                        binaire=binaire+reconnue.genererBin(listeEtiquette,ligne)+"\n";

                                        reconnue.setLine(ligne);
                                        //added by LM BEGIN
                                        this.ihm.instructionsToBeDownloaded.add(reconnue);
                                        //added by LM END

                                        //added by LM BEGIN
                                        this.ihm.codeToBeDownloaded.add(reconnue.genererBin(listeEtiquette,ligne));
                                        //added by LM END
                                }
                                else
                                {
                                        err.setText(err.getText()+"instruction "+ligne+" : Instruction non identifiée\n");
                                        noASMError=false;
                                }
                        }
                        parsInstr.finLigne();
                }
                if(noASMError){
                    s.setText(binaire);
                    //err.setText("Pas d'erreur d'assemblage");
                }
                else{
                    s.setText("NO CODE");
                    //err.setText("Erreur d'assemblage");
                    this.ihm.enSim=Ihm.ENNOTOK;
                }
        }
        //NEW added by LM BEGIN
        
         if(noASMError){
             /*
              * this.ihm.LCM3simulator.download(
                    this.ihm.instructionsToBeDownloaded,
                    this.ihm.codeToBeDownloaded,listeEtiquette);
              * 
              */
            if(checkValParam()==true){

                /*
                System.out.println(this.ihm.LCM3simulator);
                for(int i=0;i<20;i++){
                    this.ihm.LCM3simulator.oneStep();
                    if(this.ihm.LCM3simulator.numException==0){
                        System.out.println(this.ihm.LCM3simulator);
                        this.ihm.LCM3simulator.modifs.clear();
                        err.setText(this.ihm.LCM3simulator.toString());
                    }

                }*/
                err.setText("Code assembleur correct: SIMULATION POSSIBLE");
                this.ihm.enSim=Ihm.ENOK;
                this.ihm.panelRegistres.formatAff=0;
                this.ihm.LCM3simulator.reset2();
                this.ihm.LCM3simulator.download(
                    this.ihm.instructionsToBeDownloaded,
                    this.ihm.codeToBeDownloaded,listeEtiquette);
                this.ihm.panelMemoires.downloadCode(this.ihm.LCM3simulator);
                ihm.LCM3simulator.resetVar();
                ihm.initAff();
                
                
            }
            else{
                this.ihm.LCM3simulator.reset();
                this.ihm.enSim=Ihm.ENNOTOK;
                err.setText("Erreur: valeur erronée de paramètre(s)");
                System.out.println("simulation impossible");
            }
         
        }
        //NEW added by LM END 
// Premier parsage de la zone de texte pour récupérer les etiquettes */
        /*
         * while(!parsEtiq.termine()){
                String a1=parsEtiq.obtenirMot();
                if(!a1.equals("")){
                        Etiquette etiquette = new Etiquette(ligne, a1);
                        listeEtiquette.add(etiquette);
                }
                parsEtiq.passerEspace();
                if(parsEtiq.TypeParam()!=null)
                        ligne++;
                parsEtiq.finLigne();
        }
        if(err.getText().equals(""))
        {
                ligne=0;
                Parseur parsInstr=new Parseur(e.getText(),err);
                Instruction reconnue,identifiee=null;
                String binaire="";
                boolean bool=true;
         * /
         * 
         */
                /* Second parsage de la zone de texte pour récupérer les instructions */
        /*
                while(!parsInstr.termine()){
                        // Sauter l'étiquette 
                        parsInstr.obtenirMot();
                        parsInstr.passerEspace();



                        // Prendre l'instruction 
                        if((reconnue=parsInstr.TypeParam())!=null)
                        {
                                ligne++;
                                identifiee=null;
                                for(Instruction i : MainFrame.assPrincipal.getListeCommandes())
                                {
                                        if(i.compInstr(reconnue))
                                        {
                                        identifiee=i;
                                        }
                                }
                                if(identifiee!=null)
                                {
                                        reconnue.charger(identifiee);
                                        binaire=binaire+reconnue.genererBin(listeEtiquette,ligne)+"\n";
  //ici mettre identifie et code binaire dasn une liste                                      
                                }
                                else
                                {
                                        err.setText(err.getText()+"ligne "+ligne+" : Instruction non identifiée\n");
                                        bool=false;
                                }
                        }
                        parsInstr.finLigne();
                }
                if(bool)
                    s.setText(binaire);
        }
        
        // Partie Hexa
       String codeBinaire = s.getText();
       for(int i = 0; i < codeBinaire.length(); i++)
       {
         System.out.print(codeBinaire.charAt(i));  
       }
        */
    }//GEN-LAST:event_jButton1ActionPerformed
    private int getCodeInInt(String binaryCode){
        int val=0,i,w=0x8000;
        char bit;
        for(i=0;i<16;i++){
            bit=binaryCode.charAt(i);
            if(bit=='1')
                val+=w;
            w=w>>1;
        }
        return val;
    }
    public boolean checkValParam() {
        int n=0;
        
        for(Instruction i : this.ihm.instructionsToBeDownloaded){
            System.out.println("instruction:"+i.getNom()+
                    "=>"+this.ihm.codeToBeDownloaded.get(n)+
                    "="+getCodeInInt(this.ihm.codeToBeDownloaded.get(n)));
            if(i.checkValParam()==false){
                System.out.println("instruction:"+i.getNom()+
                        " ERREUR pour val instruction n°"+i.getLine());
                return false;
            }
            System.out.println("instruction:"+i.getNom()+"OK pour val");
            n++;
            
        }
        return true;
    }
     
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JColorChooser jColorChooser2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables

    public JTextPane getjTextPane1() {
        return jTextPane1;
    }

    public void setPc(int pc) {
        this.pc = pc;
    }
}
