/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelPipeline.java
 *
 * Created on 11 févr. 2010, 21:20:59
 * @author  Betty && Samira
 */

package ensea.simulateurSTM32.ihm.Panel;

//import Simulateur.Kernel.SimManager;
import ensea.simulateurSTM32.LCM3.EtatPipeline;
import ensea.simulateurSTM32.LCM3.Memory;
import ensea.simulateurSTM32.LCM3.Pipeline;
import ensea.simulateurSTM32.ihm.Ihm;
import java.awt.Color;
import java.awt.Font;
 /**
 * 
 * Permet l'affichage graphique  du Pipeline
 * 
 */

public class PanelPipeline extends javax.swing.JPanel {
        public Ihm ihm;
        int d=0;
        int m=0;
        String s2="";
        int dr2=1000;
        boolean cond=false;
    /** Creates new form PanelPipeline */
    public PanelPipeline(Ihm ihm) {
         this.ihm=ihm;
        initComponents();

    }

    public void setS2(String s2) {
        this.s2 = s2;
    }
    public void dispTime(Pipeline p){
        if(p.getnStep()>=0)
            jLabelT.setText(String.valueOf(p.getnStep()+1));
        else
            jLabelT.setText(String.valueOf("t"));
        if(p.getnStep()>=1)
            jLabelT1.setText(String.valueOf(p.getnStep()));
        else
            jLabelT1.setText(String.valueOf("t-1"));
        if(p.getnStep()>=2)
            jLabelT2.setText(String.valueOf(p.getnStep()-1));
        else
            jLabelT2.setText(String.valueOf("t-2"));
        if(p.getnStep()>=3)
            jLabelT3.setText(String.valueOf(p.getnStep()-2));
        else
            jLabelT3.setText(String.valueOf("t-3"));
    }
    void dispF(Pipeline p){
        EtatPipeline e;
        e=p.getEtat()[0];
        Memory mem=new Memory(4,4);

        //jTextFieldF0.setFont(new Font("C"));
        if(p.getnStep()>=0){
            jTextFieldF0.setBackground(e.getCouleurF());
            String buf=new String("M[0x");
            buf=buf.concat(mem.inHexa(e.getFetchPC(),8));
            buf=buf.concat("]");
            jTextFieldF0.setText(String.format(buf));
             System.out.println(e.getFetchPC());
        }
        
        else{
            jTextFieldF0.setBackground(Color.LIGHT_GRAY);
            jTextFieldF0.setText("M[0xXXXXXXXX]");
        }
        e=p.getEtat()[1];
        if(p.getnStep()>=1){
            jTextFieldF1.setBackground(e.getCouleurF());
            String buf=new String("M[0x");
            buf=buf.concat(mem.inHexa(e.getFetchPC(),8));
            buf=buf.concat("]");
            jTextFieldF1.setText(String.format(buf));
             System.out.println(e.getFetchPC());
        }
        else{
            jTextFieldF1.setBackground(Color.LIGHT_GRAY);
            jTextFieldF1.setText("M[0xXXXXXXXX]");
        }
        
        e=p.getEtat()[2];
        if(p.getnStep()>=2){
            jTextFieldF2.setBackground(e.getCouleurF());
            String buf=new String("M[0x");
            buf=buf.concat(mem.inHexa(e.getFetchPC(),8));
            buf=buf.concat("]");
            jTextFieldF2.setText(String.format(buf));
            int i=e.getFetchPC()-134217727;
            System.out.println(i);
        }
        else{
            jTextFieldF2.setBackground(Color.LIGHT_GRAY);
            jTextFieldF2.setText("M[0xXXXXXXXX]");
        }
        
        e=p.getEtat()[3];
        if(p.getnStep()>=3){
            jTextFieldF3.setBackground(e.getCouleurF());
            String buf=new String("M[0x");
            buf=buf.concat(mem.inHexa(e.getFetchPC(),8));
            buf=buf.concat("]");
            jTextFieldF3.setText(String.format(buf));
        }
        else{
            jTextFieldF3.setBackground(Color.LIGHT_GRAY);
            jTextFieldF3.setText("M[0xXXXXXXXX]");
        }
    }
    public void disp(Pipeline p){
        dispTime(p);
        dispF(p);
        dispD(p);
        dispE(p);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitre = new javax.swing.JLabel();
        jLabelFetch = new javax.swing.JLabel();
        jLabelDecode = new javax.swing.JLabel();
        jLabelExecute = new javax.swing.JLabel();
        jTextFieldF0 = new javax.swing.JTextField();
        jTextFieldD0 = new javax.swing.JTextField();
        jTextFieldE0 = new javax.swing.JTextField();
        jTextFieldF1 = new javax.swing.JTextField();
        jTextFieldD1 = new javax.swing.JTextField();
        jTextFieldE1 = new javax.swing.JTextField();
        jTextFieldF2 = new javax.swing.JTextField();
        jTextFieldD2 = new javax.swing.JTextField();
        jTextFieldE2 = new javax.swing.JTextField();
        jTextFieldF3 = new javax.swing.JTextField();
        jTextFieldD3 = new javax.swing.JTextField();
        jTextFieldE3 = new javax.swing.JTextField();
        jLabelT2 = new javax.swing.JLabel();
        jLabelT1 = new javax.swing.JLabel();
        jLabelT = new javax.swing.JLabel();
        jLabelT3 = new javax.swing.JLabel();
        jLabelT4 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelTitre.setFont(new java.awt.Font("Plantagenet Cherokee", 1, 14));
        jLabelTitre.setText("Visualisation du pipeline");

        jLabelFetch.setText("FETCH");

        jLabelDecode.setText("DECODE");

        jLabelExecute.setText("EXECUTE");

        jTextFieldF0.setBackground(new java.awt.Color(240, 240, 164));
        jTextFieldF0.setEditable(false);
        jTextFieldF0.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldF0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldF0ActionPerformed(evt);
            }
        });

        jTextFieldD0.setBackground(new java.awt.Color(255, 204, 0));
        jTextFieldD0.setEditable(false);
        jTextFieldD0.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldD0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldD0ActionPerformed(evt);
            }
        });

        jTextFieldE0.setBackground(new java.awt.Color(153, 153, 255));
        jTextFieldE0.setEditable(false);
        jTextFieldE0.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextFieldF1.setBackground(new java.awt.Color(255, 204, 0));
        jTextFieldF1.setEditable(false);
        jTextFieldF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldF1ActionPerformed(evt);
            }
        });

        jTextFieldD1.setBackground(new java.awt.Color(255, 51, 51));
        jTextFieldD1.setEditable(false);
        jTextFieldD1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextFieldE1.setBackground(new java.awt.Color(204, 255, 153));
        jTextFieldE1.setEditable(false);

        jTextFieldF2.setBackground(new java.awt.Color(255, 51, 51));
        jTextFieldF2.setEditable(false);
        jTextFieldF2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldF2ActionPerformed(evt);
            }
        });

        jTextFieldD2.setBackground(new java.awt.Color(204, 255, 153));
        jTextFieldD2.setEditable(false);

        jTextFieldE2.setBackground(new java.awt.Color(0, 255, 255));
        jTextFieldE2.setEditable(false);

        jTextFieldF3.setBackground(new java.awt.Color(204, 255, 153));
        jTextFieldF3.setEditable(false);

        jTextFieldD3.setBackground(new java.awt.Color(0, 255, 255));
        jTextFieldD3.setEditable(false);

        jTextFieldE3.setBackground(new java.awt.Color(255, 0, 255));
        jTextFieldE3.setEditable(false);

        jLabelT2.setText("t - 2");

        jLabelT1.setText("t - 1");

        jLabelT.setText("t");

        jLabelT3.setText("t - 3");

        jLabelT4.setText("t ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelTitre, javax.swing.GroupLayout.DEFAULT_SIZE, 777, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelT4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                            .addComponent(jLabelT2, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                            .addComponent(jLabelT3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                            .addComponent(jLabelT1, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                            .addComponent(jLabelT, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldF2)
                                    .addComponent(jTextFieldF1)
                                    .addComponent(jTextFieldF0, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                    .addComponent(jTextFieldF3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelFetch)
                                .addGap(38, 38, 38)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldD3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                    .addComponent(jTextFieldD2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                    .addComponent(jTextFieldD0, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                    .addComponent(jTextFieldD1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                                .addGap(9, 9, 9))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabelDecode, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldE0, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                            .addComponent(jTextFieldE2, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                            .addComponent(jTextFieldE1, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                            .addComponent(jLabelExecute, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                            .addComponent(jTextFieldE3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(481, 481, 481))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDecode)
                    .addComponent(jLabelExecute)
                    .addComponent(jLabelT4)
                    .addComponent(jLabelFetch, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldF3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelT3)
                    .addComponent(jTextFieldD3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldE3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelT2)
                    .addComponent(jTextFieldF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldD2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldE2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelT1)
                    .addComponent(jTextFieldF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldE1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelT)
                            .addComponent(jTextFieldF0, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldE0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldD0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(59, 59, 59))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldF0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldF0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldF0ActionPerformed

    private void jTextFieldF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldF1ActionPerformed

    private void jTextFieldD0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldD0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldD0ActionPerformed

    private void jTextFieldF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldF2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldF2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelDecode;
    private javax.swing.JLabel jLabelExecute;
    private javax.swing.JLabel jLabelFetch;
    private javax.swing.JLabel jLabelT;
    private javax.swing.JLabel jLabelT1;
    private javax.swing.JLabel jLabelT2;
    private javax.swing.JLabel jLabelT3;
    private javax.swing.JLabel jLabelT4;
    private javax.swing.JLabel jLabelTitre;
    private javax.swing.JTextField jTextFieldD0;
    private javax.swing.JTextField jTextFieldD1;
    private javax.swing.JTextField jTextFieldD2;
    private javax.swing.JTextField jTextFieldD3;
    private javax.swing.JTextField jTextFieldE0;
    private javax.swing.JTextField jTextFieldE1;
    private javax.swing.JTextField jTextFieldE2;
    private javax.swing.JTextField jTextFieldE3;
    private javax.swing.JTextField jTextFieldF0;
    private javax.swing.JTextField jTextFieldF1;
    private javax.swing.JTextField jTextFieldF2;
    private javax.swing.JTextField jTextFieldF3;
    // End of variables declaration//GEN-END:variables




    private void dispD(Pipeline p) {
        EtatPipeline e;
        e=p.getEtat()[0];
        Memory mem=new Memory(4,4);

        if(p.getnStep()>=1){
            jTextFieldD0.setBackground(e.getCouleurD());
            String buf=new String("0x");
            buf=buf.concat(mem.inHexa(e.getDecodeCode(),4));
            jTextFieldD0.setText(String.format(buf));
        }
        else{
            jTextFieldD0.setBackground(Color.LIGHT_GRAY);
            jTextFieldD0.setText("0xXXXX");
        }
        
        e=p.getEtat()[1];
        if(p.getnStep()>=2){
            jTextFieldD1.setBackground(e.getCouleurD());
            String buf=new String("0x");
            buf=buf.concat(mem.inHexa(e.getDecodeCode(),4));
            jTextFieldD1.setText(String.format(buf));
        }
        else{
            jTextFieldD1.setBackground(Color.LIGHT_GRAY);
            jTextFieldD1.setText("0xXXXX");
        }
        
        e=p.getEtat()[2];
        if(p.getnStep()>=3){
            jTextFieldD2.setBackground(e.getCouleurD());
            String buf=new String("0x");
            buf=buf.concat(mem.inHexa(e.getDecodeCode(),4));
            jTextFieldD2.setText(String.format(buf));
        }
        else{
            jTextFieldD2.setBackground(Color.LIGHT_GRAY);
            jTextFieldD2.setText("0xXXXX");
        }
        
        e=p.getEtat()[3];
        if(p.getnStep()>=4){
            jTextFieldD3.setBackground(e.getCouleurD());
            String buf=new String("0x");
            buf=buf.concat(mem.inHexa(e.getDecodeCode(),4));
            jTextFieldD3.setText(String.format(buf));
        }
        else{
            jTextFieldD3.setBackground(Color.LIGHT_GRAY);
            jTextFieldD3.setText("0xXXXX");
        }
    }
       private void dispE(Pipeline p) {
        EtatPipeline e;
        e=p.getEtat()[0];
        Memory mem=new Memory(4,4);

        if(p.getnStep()>=1){
            jTextFieldE0.setBackground(e.getCouleurE());
            String buf=new String("");
            buf=buf.concat(e.getExecuteInstruction());
            jTextFieldE0.setText(String.format(buf));
        }
        else{
            jTextFieldE0.setBackground(Color.LIGHT_GRAY);
            jTextFieldE0.setText("XXX XX ");
        }
        
        e=p.getEtat()[1];
        if(p.getnStep()>=2){
            jTextFieldE1.setBackground(e.getCouleurE());
            String buf=new String("");
            buf=buf.concat(e.getExecuteInstruction());
            jTextFieldE1.setText(String.format(buf));
        }
        else{
            jTextFieldE1.setBackground(Color.LIGHT_GRAY);
            jTextFieldE1.setText("XXX XX ");
        }
        
        e=p.getEtat()[2];
        if(p.getnStep()>=3){
            jTextFieldE2.setBackground(e.getCouleurE());
            String buf=new String("");
            buf=buf.concat(e.getExecuteInstruction());
            jTextFieldE2.setText(String.format(buf));
        }
        else{
            jTextFieldE2.setBackground(Color.LIGHT_GRAY);
            jTextFieldE2.setText("XXX XX ");
        }
        
        e=p.getEtat()[3];
        if(p.getnStep()>=4){
            jTextFieldE3.setBackground(e.getCouleurE());
            String buf=new String("");
            buf=buf.concat(e.getExecuteInstruction());
            jTextFieldE3.setText(String.format(buf));
        }
        else{
            jTextFieldE3.setBackground(Color.LIGHT_GRAY);
            jTextFieldE3.setText("XXX XX ");
        }
    }
}
