/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelEdition.java
 *
 * Created on 11 févr. 2010, 22:41:55
 */

package ensea.simulateurSTM32.ihm.Panel;
import ensea.simulateurSTM32.LCM3.Memory;
import ensea.simulateurSTM32.LCM3.RAM;
import ensea.simulateurSTM32.LCM3.SimLCM3;
import ensea.simulateurSTM32.ihm.Ihm;
import java.awt.Color;
import javax.swing.JTextField;
/**
 *
 * Permet l'affichage de la RAM -Permettra également d'éditer la RAM
 */
public class PanelRAM extends javax.swing.JPanel {

    Ihm ihm;
    int a=0;
    int b=0;

    /** Creates new form PanelEdition */
    public PanelRAM(Ihm ihm) {
        initComponents();
        this.initComponents2();
        this.ihm=ihm;
    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jFileChooser1 = new javax.swing.JFileChooser();
        jScrollPaneRAM = new javax.swing.JScrollPane();
        jTableRAM = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        setPreferredSize(new java.awt.Dimension(180, 234));
        setLayout(new java.awt.GridBagLayout());

        jTableRAM.setBackground(new java.awt.Color(204, 255, 153));
        jTableRAM.setFont(new java.awt.Font("Courier New", 0, 11)); // NOI18N
        jTableRAM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Adresse", "Contenu entier", "Contenu hexadécimal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableRAM.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTableRAM.setSelectionForeground(new java.awt.Color(255, 51, 0));
        jTableRAM.getTableHeader().setReorderingAllowed(false);
        jScrollPaneRAM.setViewportView(jTableRAM);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 429;
        gridBagConstraints.ipady = 400;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(12, 11, 12, 11);
        add(jScrollPaneRAM, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JScrollPane jScrollPaneRAM;
    private javax.swing.JTable jTableRAM;
    // End of variables declaration//GEN-END:variables

    private void initComponents2() {
        //jTableRAM.getColumnModel().getColumn(0).setResizable(false);
  //     jTableRAM.getColumnModel().getColumn(1).setResizable(false);
    }
    public void dispVal(int i, int val){
        this.jTableRAM.setValueAt(String.valueOf(val),i,1);
    }
    public void dispAdr(int i, int adr){
        Memory mem=new Memory(4,4);
        String buf="0x";
        buf=buf.concat(mem.inHexa(adr,8));
        this.jTableRAM.setValueAt(buf,i,0);
    }


    public void initAff(SimLCM3 LCM3simulator) {
        int i,val,adr;
        this.jTableRAM.setForeground(Color.blue);
        for(i=0;i<10;i++){
            adr=RAM.BASERAM+i*4;
            val=LCM3simulator.getTheRAM().readW(RAM.BASERAM+i*4);
            dispAdr(i,adr);
            dispVal(i,val);
        } 
    }
    public void aff(SimLCM3 LCM3simulator) {
        int i,val,adr;
        this.jTableRAM.setForeground(Color.black);
        for(i=0;i<10;i++){
            adr=RAM.BASERAM+i*4;
            val=LCM3simulator.getTheRAM().readW(RAM.BASERAM+i*4);
            dispAdr(i,adr);
            dispVal(i,val);
        } 
    }
    
    public void affRouge(int adr, int val) {
        int i;
        i=(adr-RAM.BASERAM)/4;
        this.jTableRAM.setForeground(Color.red);
        dispAdr(i,adr);
        dispVal(i,val); 
    }
}
