/*
 * PanelMemoires.java
 *
 * 
 */

package ensea.simulateurSTM32.ihm.Panel;
//import Simulateur.Kernel.MemoireCode;
import ensea.simulateurSTM32.LCM3.Memory;
import ensea.simulateurSTM32.LCM3.SimLCM3;
import ensea.simulateurSTM32.parseur.Instruction;
import java.awt.Color;
import java.awt.Font;
import javax.swing.ButtonGroup;
import javax.swing.JTable;

/**
 *  Permet l'affichage de la mémoire ROM
 * @author  Guillaume-Vincent
 */
public class PanelMemoires extends javax.swing.JPanel {

    public ButtonGroup groupe;
  
    public int debutTableMemoire1;
    public int debutTableMemoire2;
  //  public MemoireCode rom;
    public int click=0;
    int a=0;
    int b=0;
   // public SimManager sim;
    /** Creates new form PanelMemoires */
    
    public PanelMemoires() { // public PanelMemoires(MemoireCode mem) {

        groupe= new ButtonGroup();
        
        debutTableMemoire1 = 0x20000000;
        debutTableMemoire2 = 0x08000000;// 

        initComponents();
        initComponents2();

         //rom= new MemoireCode();
       //  this.rom=mem;

         String s=Integer.toHexString(this.debutTableMemoire1);
         s= "000"+s;
         s=s.substring(s.length()-4,s.length());
        //this.jTextField20.setText(s);
        //this.jTextField21.setText(Integer.toHexString(this.debutTableMemoire2));
        for(int i=0; i<12;i++){
            jTableROM.setValueAt("0x0000", i, 1);}
        for(int i=0; i<12;i++){
       // jTableRAM.setValueAt("0x0000", i, 1)
            ;}
      //  this.setJTableMem(1);
      //  this.setJTableMem(2);


        //groupe.add(jRadioButton1);
        //groupe.add(jRadioButton2);
        
    }
    
    public void modifyROM(){
        jTableROM.setValueAt("oui", 2, 2);
        
        
    }    
    // Soupe Maison
    public String getText() {
        return jTextPaneCodeBin.getText();
    }
    
    public void setText(String text) {
        this.jTextPaneCodeBin.setText(text);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPaneROM = new javax.swing.JScrollPane();
        jTableROM = new javax.swing.JTable();
        jScrollPaneCodeBin = new javax.swing.JScrollPane();
        jTextPaneCodeBin = new javax.swing.JTextPane();

        setPreferredSize(new java.awt.Dimension(449, 300));
        setLayout(new java.awt.CardLayout());

        jTabbedPane1.setPreferredSize(new java.awt.Dimension(210, 246));
        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jTableROM.setBackground(new java.awt.Color(204, 255, 255));
        jTableROM.setFont(new java.awt.Font("Courier New", 0, 11)); // NOI18N
        jTableROM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Adresse (32 bits)", "Code (16 bits)", "ASM", "Pointer"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableROM.setAutoscrolls(false);
        jTableROM.setMinimumSize(new java.awt.Dimension(100, 256));
        jTableROM.setSelectionForeground(new java.awt.Color(255, 51, 0));
        jTableROM.getTableHeader().setReorderingAllowed(false);
        jScrollPaneROM.setViewportView(jTableROM);
        jTableROM.getColumnModel().getColumn(0).setResizable(false);
        jTableROM.getColumnModel().getColumn(0).setPreferredWidth(25);
        jTableROM.getColumnModel().getColumn(1).setMinWidth(25);

        jTabbedPane1.addTab("ROM", jScrollPaneROM);

        jScrollPaneCodeBin.setViewportView(jTextPaneCodeBin);

        jTabbedPane1.addTab("CodeBinaire", jScrollPaneCodeBin);

        add(jTabbedPane1, "card2");
    }// </editor-fold>//GEN-END:initComponents

private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        // TODO add your handling code here:
          if (click ==0) click =1;
          else click= 0;

         
}//GEN-LAST:event_jTabbedPane1StateChanged
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPaneCodeBin;
    private javax.swing.JScrollPane jScrollPaneROM;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableROM;
    private javax.swing.JTextPane jTextPaneCodeBin;
    // End of variables declaration//GEN-END:variables
        
  

    private void initComponents2() {
        jTableROM.getColumnModel().getColumn(0).setMaxWidth(100);
        jTableROM.getColumnModel().getColumn(0).setMinWidth(10);
        jTableROM.getColumnModel().getColumn(0).setPreferredWidth(100);
        jTableROM.getColumnModel().getColumn(1).setMaxWidth(70);
        jTableROM.getColumnModel().getColumn(1).setMinWidth(10);
        jTableROM.getColumnModel().getColumn(1).setPreferredWidth(50);
        for(int i=0; i<16;i++){
            jTableROM.setValueAt("0x0000", i, 1);
        }
        int adr=0x08000000;
        String buf=new String();
        Memory mem=new Memory(4,4);
        for(int i=0; i<16;i++){
            buf=new String("0x");
            buf=buf.concat(mem.inHexa(adr,8));
            jTableROM.setValueAt(buf, i, 0);
            adr+=2;
        }
       //jTableROM.setFont(new java.awt.Font("Courier New", Font.ITALIC, 11));
       jTableROM.setValueAt("0x08000000", 0, 0);
       jTableROM.setFont(new java.awt.Font("Courier New", Font.BOLD, 11));

        
    }

   /**La mauvaise programmation 
     * public JTable getjTableROM() {
        return jTableROM;
    }**/

    void downloadCode(SimLCM3 LCM3simulator) {
        int val;
        String buf=new String();
        Memory mem=new Memory(4,4);
         for(int i=0; i<16;i++){
             val=LCM3simulator.getTheROM().readHW(0x08000000+2*i);
             buf=new String("0x");
             buf=buf.concat(mem.inHexa(val,4));
            jTableROM.setValueAt(buf, i, 1);
        }
        int i=0;
        for(Instruction inst : LCM3simulator.getDownloadedInstructions()){
            jTableROM.setValueAt(inst.getNomComplet(), i, 2);
            i++;
        } 
     
    }
    
    public void initAff() {
         this.jTableROM.getSelectionModel().clearSelection();
    }
    
    public void selectionnerLigne(int numeroLigne, Color couleurLigne) {
        this.initAff();
        this.jTableROM.getSelectionModel().addSelectionInterval(numeroLigne, numeroLigne);
        this.jTableROM.setSelectionBackground(couleurLigne);
    }
    
    
    
    

}
