/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelDialog.java
 *  azerty
 * Created on 13 févr. 2010, 01:12:20
 * @author  Betty && Samira
 */

package ensea.simulateurSTM32.ihm.Panel;

import javax.swing.JTextPane;

/**
 * Permet l'état du simulateur après analyse des instructions - Compilation -Assemblage
 * @author Pingoo
 */


public class PanelDialog extends javax.swing.JPanel {

    /** Creates new form PanelDialog */
    public PanelDialog() {
        initComponents();
    }
    
    // SOupe Maison
    public String getText() {
        return jTextPane1.getText();
    }
    
    public void setText(String text) {
        this.jTextPane1.setText(text);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setBackground(new java.awt.Color(255, 51, 51));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 0)));
        setMinimumSize(new java.awt.Dimension(595, 1000));
        setLayout(new java.awt.GridLayout(1, 0));

        jScrollPane1.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jScrollPane1.setInheritsPopupMenu(true);
        jScrollPane1.setOpaque(false);

        jTextPane1.setAlignmentX(10.0F);
        jTextPane1.setMinimumSize(new java.awt.Dimension(6, 120));
        jTextPane1.setPreferredSize(new java.awt.Dimension(6, 120));
        jScrollPane1.setViewportView(jTextPane1);

        add(jScrollPane1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables

    public JTextPane getjTextPane1() {
        return jTextPane1;
    }

    

}
