/*
 * Ihm.java
 *
 *
 * @author  Betty && Samira
 */

package ensea.simulateurSTM32.ihm;


import ensea.simulateurSTM32.LCM3.SimLCM3;
import java.io.*;
import javax.swing.*;
import javax.swing.JFileChooser;

//import Simulateur.Kernel.SimManager;
import ensea.simulateurSTM32.ihm.Panel.PanelDialog;
import ensea.simulateurSTM32.ihm.Panel.PanelPipeline;
import ensea.simulateurSTM32.ihm.Panel.PanelFlags;
import ensea.simulateurSTM32.ihm.Panel.PanelRAM;
import ensea.simulateurSTM32.ihm.Panel.PanelBouttons;
import ensea.simulateurSTM32.ihm.Panel.PanelMemoires;
import ensea.simulateurSTM32.ihm.Panel.PanelRegistres;
import ensea.simulateurSTM32.ihm.Panel.PanelCode;
import ensea.simulateurSTM32.parseur.Instruction;
import java.util.ArrayList;
/**
 *
 * @author  Betty &&Samira
 */
public class Ihm extends javax.swing.JFrame {

    public int adresseDebutProgramme;

    public PanelBouttons panelBouttons;
    public PanelMemoires panelMemoires;
    public PanelRegistres panelRegistres;
    public PanelFlags panelFlags;
    public PanelPipeline panelPipeline;
    public PanelDialog panelDialog;
    public PanelRAM panelRAM;
    public PanelCode panelcode;
    public ensea.simulateurSTM32.ihm.Panel.PanelAnim panelAnim;

    //added by LM BEGIN
    public ArrayList<Instruction> instructionsToBeDownloaded;
    public ArrayList<String> codeToBeDownloaded;
    public SimLCM3 LCM3simulator;
    public int enSim=0;
    public static final int ENOK = 1;
    public static final int ENNOTOK = 0;
    //added by LM END


    /** Creates new form Ihm */
    public Ihm() {
        setTitle("Simulation Microprocesseur");


        //demarage du noyau
        instructionsToBeDownloaded=new ArrayList<>();
        codeToBeDownloaded=new ArrayList<>();
        LCM3simulator=new SimLCM3();
        LCM3simulator.reset();
        //instanciation des divers Panels
        panelBouttons = new PanelBouttons(this);
        panelMemoires = new PanelMemoires();

        panelRegistres = new PanelRegistres(); // new PanelRegistres(simmanager.getRegistres(),simmanager.getFetch());
        panelRAM=new PanelRAM(this);
        panelPipeline=new PanelPipeline(this);
        panelFlags= new PanelFlags(this);
        panelDialog=new PanelDialog();
        panelcode= new PanelCode(this);



        adresseDebutProgramme=0x20000;

        initComponents();
        this.initAff();



    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LCM3 : Le simulateur made in ENSEA                                                                                         VIVE LA VOILE !!                                                                                       ");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1100, 700));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        // getContentPane().setLayout(...) — fait dans miseEnPage()

        miseEnPage();

        jMenu1.setText("Fichier");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setText("Charger code");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem5.setText("Enregistrer code ");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setText("Quitter");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edition");

        jMenuItem4.setText("Auteurs");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed

        JFileChooser chooser = new JFileChooser();

        chooser.showDialog(null,"Enregistrer");


        File fichier =chooser.getSelectedFile();
        String chaine= panelcode.getjTextPane1().getText();

        try {
            FileWriter fw = new FileWriter(fichier);
            BufferedWriter bw = new BufferedWriter(fw);
            PrintWriter fichierSortie = new PrintWriter(bw);


            fichierSortie.println(chaine);
            fichierSortie.close();
            System.out.println("Le fichier a été crée");

            panelDialog.getjTextPane1().setText("Enregistrement du fichier "+fichier.getName());

        }

        catch (Exception e){
            System.out.println(e.toString());
        }




    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed


        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File fichier =chooser.getSelectedFile();
        StringBuilder chaine= new StringBuilder();

        try{
            InputStream ips=new FileInputStream(fichier);
            InputStreamReader ipsr=new InputStreamReader(ips);
            BufferedReader br=new BufferedReader(ipsr);
            String ligne;
            while ((ligne=br.readLine())!=null){
                chaine.append(ligne).append('\n');
            }
            br.close();

            panelDialog.getjTextPane1().setText("Chargement du fichier "+fichier.getName());

        }

        catch (Exception e){
            System.out.println(e.toString());
        }

        panelcode.getjTextPane1().setText(chaine.toString());

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        JOptionPane d= new JOptionPane();
        JOptionPane.showMessageDialog(this,
                "2025-2026: Lucie HOUEL \n2015-2016: Simon DOLE & Arthur GERSTER \n2011-2012: Guillaume CHAIGNON & Vincent PINGARD \n2010-2011: Hadrian OVAZZA & Louis ROLLAND \n2009-2010: Betty BASTAREAUD & Samira ROCHDI",

                " Auteurs",
                JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
    }//GEN-LAST:event_formComponentResized



    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JMenu jMenu1;
    javax.swing.JMenu jMenu2;
    javax.swing.JMenuBar jMenuBar1;
    javax.swing.JMenuItem jMenuItem1;
    javax.swing.JMenuItem jMenuItem2;
    javax.swing.JMenuItem jMenuItem4;
    javax.swing.JMenuItem jMenuItem5;
    // End of variables declaration//GEN-END:variables


    private void miseEnPage() {
        getContentPane().setLayout(new java.awt.BorderLayout(6, 6));

        javax.swing.JPanel leftCol = new javax.swing.JPanel(new java.awt.BorderLayout(0, 4));
        leftCol.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 6, 6, 3));
        leftCol.add(panelcode, java.awt.BorderLayout.CENTER);
        panelDialog.setPreferredSize(new java.awt.Dimension(350, 300));
        leftCol.add(panelDialog, java.awt.BorderLayout.SOUTH);

        javax.swing.JPanel centerZone = new javax.swing.JPanel(new java.awt.BorderLayout(6, 6));
        centerZone.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 0, 0, 0));

        javax.swing.JPanel topBar = new javax.swing.JPanel(new java.awt.BorderLayout(6, 0));
        panelMemoires.setPreferredSize(new java.awt.Dimension(280, 220));
        panelPipeline.setPreferredSize(new java.awt.Dimension(350, 220));
        topBar.add(panelMemoires, java.awt.BorderLayout.WEST);

        topBar.add(panelMemoires, java.awt.BorderLayout.WEST);

        javax.swing.JScrollPane scrollPipeline = new javax.swing.JScrollPane();

        scrollPipeline.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        scrollPipeline.setHorizontalScrollBarPolicy(javax.swing.JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        scrollPipeline.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED); // On peut réactiver le vertical !

        panelPipeline.attachToScrollPane(scrollPipeline);

        topBar.add(scrollPipeline, java.awt.BorderLayout.CENTER);
        centerZone.add(topBar, java.awt.BorderLayout.NORTH);

        this.panelAnim = new ensea.simulateurSTM32.ihm.Panel.PanelAnim(this);
        this.panelAnim.setPreferredSize(new java.awt.Dimension(600, 300));
        centerZone.add(this.panelAnim, java.awt.BorderLayout.CENTER);

        javax.swing.JPanel btnRow = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 6));
        btnRow.add(panelBouttons);
        centerZone.add(btnRow, java.awt.BorderLayout.SOUTH);

        javax.swing.JPanel rightCol = new javax.swing.JPanel(new java.awt.BorderLayout(0, 4));
        rightCol.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 0, 6, 6));
        rightCol.setPreferredSize(new java.awt.Dimension(250, 100));

        panelFlags.setPreferredSize(new java.awt.Dimension(210, 44));
        rightCol.add(panelFlags, java.awt.BorderLayout.NORTH);

        rightCol.add(new javax.swing.JPanel(), java.awt.BorderLayout.CENTER);

        javax.swing.JPanel rightBottomContainer = new javax.swing.JPanel(new java.awt.BorderLayout(0, 0));

        panelRegistres.setPreferredSize(new java.awt.Dimension(210, 300));
        rightBottomContainer.add(panelRegistres, java.awt.BorderLayout.NORTH);

        panelRAM.setPreferredSize(new java.awt.Dimension(210, 220));
        rightBottomContainer.add(panelRAM, java.awt.BorderLayout.SOUTH);

        rightCol.add(rightBottomContainer, java.awt.BorderLayout.SOUTH);


        javax.swing.JSplitPane splitPane = new javax.swing.JSplitPane(javax.swing.JSplitPane.HORIZONTAL_SPLIT, leftCol, centerZone);
        splitPane.setOneTouchExpandable(true);
        splitPane.setDividerLocation(380);

        getContentPane().add(splitPane, java.awt.BorderLayout.CENTER);
        getContentPane().add(rightCol, java.awt.BorderLayout.EAST);
    }

    public void initAff(){
        if (panelPipeline != null) {
            panelPipeline.reset();
        }
        panelRegistres.initAff();
        panelRAM.initAff(this.LCM3simulator);
        panelPipeline.disp(this.LCM3simulator.thePipe);
        panelFlags.affFlags(0, 0, 0, 0);
        panelBouttons.initAff();
        panelMemoires.initAff();
        SimLCM3.setBouttons(panelBouttons);

        if (this.panelAnim != null) {
            this.panelAnim.disp(this.LCM3simulator.thePipe);
        }

    }

}